# see: https://www.drupal.org/docs/8/api/entity-api/creating-a-custom-content-type-in-drupal-8

langcode: en
status: true
dependencies: {  }
id: ''
field_name: ''
entity_type: node
bundle: ''
label: ''
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
    display_summary: true
#TODO: Find basic fields.
field_type: text_with_summary