# see: https://www.drupal.org/docs/8/api/entity-api/creating-a-custom-content-type-in-drupal-8

langcode: en
status: true
dependencies: {  }
name: ''
type: ''
description: ''
help: ''
new_revision: true
preview_mode: 1
display_submitted: true