# see: https://www.drupal.org/docs/8/api/entity-api/creating-a-custom-content-type-in-drupal-8

langcode: en
status: true
dependencies:
  module:
    - menu_ui
third_party_settings:
  menu_ui:
    available_menus: {  }
    parent: ''
name: ''
type: ''
description: ''
help: ''
new_revision: false
preview_mode: 1
display_submitted: false